"""Analyze full-MSWC phase-1 matrix logs and create report artifacts.

The script parses training logs generated by the matrix/resume wrappers. For
each experiment it selects the epoch with the best GSC-dev ACC@1%FAR, then
exports a ranked table and comparison plots.
"""

from __future__ import annotations

import argparse
import csv
import math
import re
from dataclasses import dataclass, field
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


START_RE = re.compile(
    r"Starting(?:/resuming)? experiment: (?P<tag>\S+) "
    r"model=(?P<model>\S+) frontend=(?P<frontend>\S+) "
    r"loss=(?P<loss>\S+) edge_tau=(?P<edge_tau>\S+)"
)
EPOCH_RE = re.compile(r"Epoch (?P<epoch>\d+)/(?P<total>\d+) \| loss=(?P<loss>[0-9.]+)")
VAL_RE = re.compile(r"Val: AUC=(?P<auc>[0-9.]+), ACC=(?P<acc>[0-9.]+)")
RUN_METRIC_RE = re.compile(
    r"AUC=(?P<auc>[0-9.]+), EER=(?P<eer>[0-9.]+), "
    r"FRR@1\.0%FAR=(?P<frr1>[0-9.]+), open-set-acc=(?P<open>[0-9.]+), "
    r"keyword-acc=(?P<keyword>[0-9.]+), F1=(?P<f1>[0-9.]+)"
)
GSC_RE = re.compile(
    r"GSC-dev: ACC@1%FAR=(?P<acc1>[0-9.]+), "
    r"ACC@5%FAR=(?P<acc5>[0-9.]+), FRR@5%=(?P<frr5>[0-9.]+)"
)
PARAM_RE = re.compile(
    r"\[INFO\]\s+(?P<model>\S+): (?P<params>\d+) parameters, "
    r"feature_type=(?P<feature>\S+), frontend_type=(?P<frontend>\S+)"
)


@dataclass
class EpochMetrics:
    epoch: int
    train_loss: float
    val_auc: float | None = None
    val_acc: float | None = None
    run_metrics: list[dict[str, float]] = field(default_factory=list)
    gsc_acc1: float | None = None
    gsc_acc5: float | None = None
    frr5: float | None = None


@dataclass
class Experiment:
    run_tag: str
    model_family: str
    frontend: str
    loss: str
    edge_tau: str
    param_count: int | None = None
    epochs: list[EpochMetrics] = field(default_factory=list)


def parse_logs(log_paths: list[Path]) -> dict[str, Experiment]:
    experiments: dict[str, Experiment] = {}
    current: Experiment | None = None
    current_epoch: EpochMetrics | None = None

    for path in log_paths:
        text = path.read_text(encoding="utf-8", errors="replace").replace("\r", "\n")
        for line in text.splitlines():
            if match := START_RE.search(line):
                tag = match.group("tag")
                current = experiments.setdefault(
                    tag,
                    Experiment(
                        run_tag=tag,
                        model_family=match.group("model"),
                        frontend=match.group("frontend"),
                        loss=match.group("loss"),
                        edge_tau="" if match.group("edge_tau") == "none" else match.group("edge_tau"),
                    ),
                )
                current_epoch = None
                continue

            if current is None:
                continue

            if match := PARAM_RE.search(line):
                current.param_count = int(match.group("params"))
                continue

            if match := EPOCH_RE.search(line):
                current_epoch = EpochMetrics(
                    epoch=int(match.group("epoch")),
                    train_loss=float(match.group("loss")),
                )
                current.epochs.append(current_epoch)
                continue

            if current_epoch is None:
                continue

            if match := VAL_RE.search(line):
                current_epoch.val_auc = float(match.group("auc"))
                current_epoch.val_acc = float(match.group("acc"))
                continue

            if match := RUN_METRIC_RE.search(line):
                current_epoch.run_metrics.append(
                    {
                        "run_auc": float(match.group("auc")),
                        "eer": float(match.group("eer")),
                        "frr1": float(match.group("frr1")),
                        "open_set_acc": float(match.group("open")),
                        "keyword_acc": float(match.group("keyword")),
                        "f1": float(match.group("f1")),
                    }
                )
                continue

            if match := GSC_RE.search(line):
                current_epoch.gsc_acc1 = float(match.group("acc1"))
                current_epoch.gsc_acc5 = float(match.group("acc5"))
                current_epoch.frr5 = float(match.group("frr5"))

    return experiments


def load_status(tsv_paths: list[Path]) -> dict[str, dict[str, str]]:
    status: dict[str, dict[str, str]] = {}
    for path in tsv_paths:
        if not path.exists():
            continue
        with path.open("r", encoding="utf-8", newline="") as f:
            for row in csv.DictReader(f, delimiter="\t"):
                status[row["run_tag"]] = row
    return status


def display_model(model_family: str, edge_tau: str) -> str:
    if model_family == "dscnn":
        return "DSCNN-L"
    if model_family == "edgespot_full":
        return f"EdgeSpotFull T{edge_tau or '4'}"
    return model_family


def display_frontend(frontend: str) -> str:
    return {"mfcc": "MFCC", "mel_pcen": "PCEN", "mel": "Mel"}.get(frontend, frontend)


def display_loss(loss: str) -> str:
    return {
        "triplet": "Triplet",
        "scaf": "SCAF",
        "ge2e": "GE2E",
        "scaf_ge2e": "SCAF+GE2E",
    }.get(loss, loss)


def mean_metric(epoch: EpochMetrics, key: str) -> float:
    values = [m[key] for m in epoch.run_metrics if key in m]
    return float(np.mean(values)) if values else math.nan


def std_metric(epoch: EpochMetrics, key: str) -> float:
    values = [m[key] for m in epoch.run_metrics if key in m]
    return float(np.std(values, ddof=1)) if len(values) > 1 else math.nan


def build_table(experiments: dict[str, Experiment], status: dict[str, dict[str, str]]) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for exp in experiments.values():
        valid_epochs = [e for e in exp.epochs if e.gsc_acc1 is not None]
        if not valid_epochs:
            continue
        best = max(valid_epochs, key=lambda e: (e.gsc_acc1 or -1.0, e.epoch))
        st = status.get(exp.run_tag, {})
        model = display_model(exp.model_family, exp.edge_tau)
        frontend = display_frontend(exp.frontend)
        loss = display_loss(exp.loss)
        rows.append(
            {
                "run_tag": exp.run_tag,
                "combo": f"{model} + {frontend} + {loss}",
                "model": model,
                "frontend": frontend,
                "loss": loss,
                "status": st.get("status", ""),
                "param_count": exp.param_count,
                "best_epoch": best.epoch,
                "acc1_far": best.gsc_acc1,
                "acc5_far": best.gsc_acc5,
                "frr5_far": best.frr5,
                "val_auc": best.val_auc,
                "val_acc": best.val_acc,
                "gsc_auc_mean": mean_metric(best, "run_auc"),
                "gsc_auc_std": std_metric(best, "run_auc"),
                "eer_mean": mean_metric(best, "eer"),
                "eer_std": std_metric(best, "eer"),
                "frr1_mean": mean_metric(best, "frr1"),
                "open_set_acc_mean": mean_metric(best, "open_set_acc"),
                "keyword_acc_mean": mean_metric(best, "keyword_acc"),
                "f1_mean": mean_metric(best, "f1"),
                "started_at": st.get("started_at", ""),
                "finished_at": st.get("finished_at", ""),
            }
        )
    df = pd.DataFrame(rows)
    if df.empty:
        return df
    order_loss = {"Triplet": 0, "SCAF": 1, "GE2E": 2, "SCAF+GE2E": 3}
    order_model = {"DSCNN-L": 0, "EdgeSpotFull T4": 1}
    order_frontend = {"MFCC": 0, "PCEN": 1}
    df["loss_order"] = df["loss"].map(order_loss)
    df["model_order"] = df["model"].map(order_model)
    df["frontend_order"] = df["frontend"].map(order_frontend)
    return df.sort_values(["model_order", "frontend_order", "loss_order"]).reset_index(drop=True)


def pct(x: float) -> float:
    return round(float(x) * 100.0, 2)


def save_tables(df: pd.DataFrame, out_dir: Path) -> None:
    df.to_csv(out_dir / "matrix_best_epoch_metrics.csv", index=False)
    md = df.copy()
    metric_cols = [
        "acc1_far",
        "acc5_far",
        "frr5_far",
        "val_auc",
        "val_acc",
        "gsc_auc_mean",
        "eer_mean",
        "open_set_acc_mean",
        "keyword_acc_mean",
        "f1_mean",
    ]
    for col in metric_cols:
        md[col] = md[col].map(lambda v: "" if pd.isna(v) else f"{pct(v):.2f}%")
    keep = [
        "combo",
        "status",
        "param_count",
        "best_epoch",
        "acc1_far",
        "acc5_far",
        "frr5_far",
        "gsc_auc_mean",
        "eer_mean",
        "open_set_acc_mean",
        "keyword_acc_mean",
        "f1_mean",
    ]
    (out_dir / "matrix_best_epoch_metrics.md").write_text(
        markdown_table(md[keep]),
        encoding="utf-8",
    )


def save_det_summary_tables(df: pd.DataFrame, out_dir: Path) -> pd.DataFrame:
    det = df.copy()
    det["rank_by_eer"] = det["eer_mean"].rank(method="min", ascending=True).astype(int)
    det["recall_at_1far"] = 1.0 - det["frr1_mean"]
    det["recall_at_5far"] = 1.0 - det["frr5_far"]
    det = det.sort_values(["eer_mean", "frr5_far", "acc1_far"], ascending=[True, True, False])

    keep = [
        "rank_by_eer",
        "combo",
        "best_epoch",
        "gsc_auc_mean",
        "eer_mean",
        "frr1_mean",
        "frr5_far",
        "recall_at_1far",
        "recall_at_5far",
        "acc1_far",
        "acc5_far",
    ]
    det[keep].to_csv(out_dir / "det_curve_summary.csv", index=False)

    md = det[keep].copy()
    md = md.rename(
        columns={
            "rank_by_eer": "rank_eer",
            "gsc_auc_mean": "AUC",
            "eer_mean": "EER",
            "frr1_mean": "FRR@1%FAR",
            "frr5_far": "FRR@5%FAR",
            "recall_at_1far": "Recall@1%FAR",
            "recall_at_5far": "Recall@5%FAR",
            "acc1_far": "ACC@1%FAR",
            "acc5_far": "ACC@5%FAR",
        }
    )
    metric_cols = [
        "AUC",
        "EER",
        "FRR@1%FAR",
        "FRR@5%FAR",
        "Recall@1%FAR",
        "Recall@5%FAR",
        "ACC@1%FAR",
        "ACC@5%FAR",
    ]
    for col in metric_cols:
        md[col] = md[col].map(lambda v: "" if pd.isna(v) else f"{pct(v):.2f}%")
    note = (
        "DET summary from best checkpoint per experiment. Lower EER/FRR is better; "
        "higher AUC/Recall/ACC is better. Full threshold-by-threshold DET curves "
        "require saved raw scores, which are not present in these phase-1 logs.\n\n"
    )
    (out_dir / "det_curve_summary.md").write_text(note + markdown_table(md), encoding="utf-8")
    return det


def markdown_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    rows = [[str(row[col]) for col in cols] for _, row in df.iterrows()]
    widths = [
        max(len(str(col)), *(len(row[i]) for row in rows))
        for i, col in enumerate(cols)
    ]
    header = "| " + " | ".join(str(col).ljust(widths[i]) for i, col in enumerate(cols)) + " |"
    sep = "| " + " | ".join("-" * widths[i] for i in range(len(cols))) + " |"
    body = [
        "| " + " | ".join(row[i].ljust(widths[i]) for i in range(len(cols))) + " |"
        for row in rows
    ]
    return "\n".join([header, sep, *body])


def metric_at(df: pd.DataFrame, model: str, frontend: str, loss: str) -> pd.Series | None:
    hit = df[(df["model"] == model) & (df["frontend"] == frontend) & (df["loss"] == loss)]
    if hit.empty:
        return None
    return hit.iloc[0]


def add_effect_row(
    rows: list[dict[str, object]],
    effect: str,
    scope: str,
    baseline: pd.Series,
    candidate: pd.Series,
    note: str,
) -> None:
    rows.append(
        {
            "effect": effect,
            "scope": scope,
            "baseline": baseline["combo"],
            "candidate": candidate["combo"],
            "baseline_acc1_far": baseline["acc1_far"],
            "candidate_acc1_far": candidate["acc1_far"],
            "delta_acc1_pp": (candidate["acc1_far"] - baseline["acc1_far"]) * 100.0,
            "baseline_acc5_far": baseline["acc5_far"],
            "candidate_acc5_far": candidate["acc5_far"],
            "delta_acc5_pp": (candidate["acc5_far"] - baseline["acc5_far"]) * 100.0,
            "baseline_frr5_far": baseline["frr5_far"],
            "candidate_frr5_far": candidate["frr5_far"],
            "delta_frr5_pp": (candidate["frr5_far"] - baseline["frr5_far"]) * 100.0,
            "baseline_f1": baseline["f1_mean"],
            "candidate_f1": candidate["f1_mean"],
            "delta_f1_pp": (candidate["f1_mean"] - baseline["f1_mean"]) * 100.0,
            "note": note,
        }
    )


def save_effect_tables(df: pd.DataFrame, out_dir: Path) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    models = ["DSCNN-L", "EdgeSpotFull T4"]
    frontends = ["MFCC", "PCEN"]
    losses = ["Triplet", "SCAF", "GE2E", "SCAF+GE2E"]

    for model in models:
        for loss in losses:
            baseline = metric_at(df, model, "MFCC", loss)
            candidate = metric_at(df, model, "PCEN", loss)
            if baseline is not None and candidate is not None:
                add_effect_row(
                    rows,
                    "PCEN vs MFCC",
                    f"{model} + {loss}",
                    baseline,
                    candidate,
                    "Tác động của frontend khi giữ nguyên model và loss.",
                )

    for model in models:
        for frontend in frontends:
            triplet = metric_at(df, model, frontend, "Triplet")
            ge2e = metric_at(df, model, frontend, "GE2E")
            if triplet is not None and ge2e is not None:
                add_effect_row(
                    rows,
                    "GE2E vs Triplet",
                    f"{model} + {frontend}",
                    triplet,
                    ge2e,
                    "Tác động của loss centroid/prototype so với loss pairwise.",
                )
            scaf = metric_at(df, model, frontend, "SCAF")
            scaf_ge2e = metric_at(df, model, frontend, "SCAF+GE2E")
            if scaf is not None and scaf_ge2e is not None:
                add_effect_row(
                    rows,
                    "SCAF+GE2E vs SCAF",
                    f"{model} + {frontend}",
                    scaf,
                    scaf_ge2e,
                    "Tác động khi thêm GE2E vào SCAF với trọng số hiện tại.",
                )
            if ge2e is not None and scaf_ge2e is not None:
                add_effect_row(
                    rows,
                    "SCAF+GE2E vs GE2E",
                    f"{model} + {frontend}",
                    ge2e,
                    scaf_ge2e,
                    "Kiểm tra liệu hybrid hiện tại có tốt hơn GE2E đơn lẻ hay không.",
                )

    for frontend in frontends:
        for loss in losses:
            baseline = metric_at(df, "DSCNN-L", frontend, loss)
            candidate = metric_at(df, "EdgeSpotFull T4", frontend, loss)
            if baseline is not None and candidate is not None:
                add_effect_row(
                    rows,
                    "EdgeSpotFull vs DSCNN",
                    f"{frontend} + {loss}",
                    baseline,
                    candidate,
                    "Tác động của backbone khi giữ nguyên frontend và loss.",
                )

    effect_df = pd.DataFrame(rows)
    if effect_df.empty:
        return effect_df

    effect_df.to_csv(out_dir / "matrix_effect_deltas.csv", index=False)
    md = effect_df.copy()
    for col in [
        "baseline_acc1_far",
        "candidate_acc1_far",
        "baseline_acc5_far",
        "candidate_acc5_far",
        "baseline_frr5_far",
        "candidate_frr5_far",
        "baseline_f1",
        "candidate_f1",
    ]:
        md[col] = md[col].map(lambda v: f"{pct(v):.2f}%")
    for col in ["delta_acc1_pp", "delta_acc5_pp", "delta_frr5_pp", "delta_f1_pp"]:
        md[col] = md[col].map(lambda v: f"{v:+.2f} pp")
    keep = [
        "effect",
        "scope",
        "delta_acc1_pp",
        "delta_acc5_pp",
        "delta_frr5_pp",
        "delta_f1_pp",
        "note",
    ]
    (out_dir / "matrix_effect_deltas.md").write_text(markdown_table(md[keep]), encoding="utf-8")
    return effect_df


def save_plots(df: pd.DataFrame, effect_df: pd.DataFrame, out_dir: Path) -> None:
    sns.set_theme(style="whitegrid", font_scale=0.92)

    plot_df = df.copy()
    plot_df["ACC@1%FAR (%)"] = plot_df["acc1_far"] * 100.0
    plot_df["ACC@5%FAR (%)"] = plot_df["acc5_far"] * 100.0
    plot_df["F1 (%)"] = plot_df["f1_mean"] * 100.0
    plot_df["Keyword ACC (%)"] = plot_df["keyword_acc_mean"] * 100.0
    plot_df["Recall@5%FAR (%)"] = (1.0 - plot_df["frr5_far"]) * 100.0
    plot_df["family"] = plot_df["model"] + " + " + plot_df["frontend"]

    ranked = plot_df.sort_values("ACC@1%FAR (%)", ascending=True)
    colors = sns.color_palette("Set2", n_colors=ranked["family"].nunique())
    family_palette = dict(zip(ranked["family"].drop_duplicates(), colors))
    fig, ax = plt.subplots(figsize=(11, 8))
    sns.barplot(
        data=ranked,
        y="combo",
        x="ACC@1%FAR (%)",
        hue="family",
        dodge=False,
        palette=family_palette,
        ax=ax,
    )
    ax.set_title("Full MSWC Phase-1: Best GSC-dev ACC@1%FAR by Combination")
    ax.set_xlabel("ACC@1%FAR (%) - higher is better")
    ax.set_ylabel("")
    ax.set_xlim(68, max(74, ranked["ACC@1%FAR (%)"].max() + 1.0))
    for container in ax.containers:
        ax.bar_label(container, fmt="%.2f", padding=3, fontsize=8)
    ax.legend(title="Model + Frontend", loc="lower right")
    fig.tight_layout()
    fig.savefig(out_dir / "acc1far_ranked_bar.png", dpi=220)
    plt.close(fig)

    heat = plot_df.pivot_table(
        index="family",
        columns="loss",
        values="ACC@1%FAR (%)",
        aggfunc="max",
    )
    heat = heat.reindex(
        ["DSCNN-L + MFCC", "DSCNN-L + PCEN", "EdgeSpotFull T4 + MFCC", "EdgeSpotFull T4 + PCEN"]
    )
    heat = heat[["Triplet", "SCAF", "GE2E", "SCAF+GE2E"]]
    fig, ax = plt.subplots(figsize=(9.5, 4.8))
    sns.heatmap(
        heat,
        annot=True,
        fmt=".2f",
        cmap="YlGnBu",
        cbar_kws={"label": "ACC@1%FAR (%)"},
        ax=ax,
    )
    ax.set_title("Model/Frontend/Loss Interaction - ACC@1%FAR")
    ax.set_xlabel("Training loss")
    ax.set_ylabel("Model + frontend")
    fig.tight_layout()
    fig.savefig(out_dir / "acc1far_interaction_heatmap.png", dpi=220)
    plt.close(fig)

    metric_df = plot_df.copy()
    metric_cols = {
        "ACC@1%FAR": "acc1_far",
        "ACC@5%FAR": "acc5_far",
        "AUC": "gsc_auc_mean",
        "Open-set ACC": "open_set_acc_mean",
        "Keyword ACC": "keyword_acc_mean",
        "F1": "f1_mean",
        "1 - EER": None,
        "1 - FRR@5%": None,
    }
    matrix = pd.DataFrame(index=metric_df["combo"])
    for label, col in metric_cols.items():
        if label == "1 - EER":
            matrix[label] = (1.0 - metric_df["eer_mean"].to_numpy()) * 100.0
        elif label == "1 - FRR@5%":
            matrix[label] = (1.0 - metric_df["frr5_far"].to_numpy()) * 100.0
        else:
            matrix[label] = metric_df[col].to_numpy() * 100.0
    matrix = matrix.loc[plot_df.sort_values("acc1_far", ascending=False)["combo"]]
    fig, ax = plt.subplots(figsize=(11.5, 8.5))
    sns.heatmap(
        matrix,
        annot=True,
        fmt=".1f",
        cmap="viridis",
        cbar_kws={"label": "Percent / transformed percent (higher is better)"},
        ax=ax,
    )
    ax.set_title("All Comparable Metrics at Best Epoch")
    ax.set_xlabel("")
    ax.set_ylabel("")
    fig.tight_layout()
    fig.savefig(out_dir / "all_metric_heatmap.png", dpi=220)
    plt.close(fig)

    det_matrix = pd.DataFrame(index=metric_df["combo"])
    det_matrix["AUC"] = metric_df["gsc_auc_mean"].to_numpy() * 100.0
    det_matrix["EER"] = metric_df["eer_mean"].to_numpy() * 100.0
    det_matrix["FRR@1%FAR"] = metric_df["frr1_mean"].to_numpy() * 100.0
    det_matrix["FRR@5%FAR"] = metric_df["frr5_far"].to_numpy() * 100.0
    det_matrix["Recall@1%FAR"] = (1.0 - metric_df["frr1_mean"].to_numpy()) * 100.0
    det_matrix["Recall@5%FAR"] = (1.0 - metric_df["frr5_far"].to_numpy()) * 100.0
    det_matrix = det_matrix.loc[plot_df.sort_values("eer_mean", ascending=True)["combo"]]
    fig, ax = plt.subplots(figsize=(10.5, 8.5))
    sns.heatmap(
        det_matrix,
        annot=True,
        fmt=".1f",
        cmap="mako_r",
        cbar_kws={"label": "Percent"},
        ax=ax,
    )
    ax.set_title("DET Summary Table - Best Epoch")
    ax.set_xlabel("")
    ax.set_ylabel("")
    fig.tight_layout()
    fig.savefig(out_dir / "det_summary_heatmap.png", dpi=220)
    plt.close(fig)

    det_points: list[dict[str, object]] = []
    for _, row in plot_df.iterrows():
        det_points.append(
            {
                "combo": row["combo"],
                "family": row["family"],
                "FAR (%)": 1.0,
                "FRR (%)": row["frr1_mean"] * 100.0,
            }
        )
        det_points.append(
            {
                "combo": row["combo"],
                "family": row["family"],
                "FAR (%)": 5.0,
                "FRR (%)": row["frr5_far"] * 100.0,
            }
        )
    det_points_df = pd.DataFrame(det_points)
    fig, ax = plt.subplots(figsize=(10.5, 7.5))
    for combo, group in det_points_df.groupby("combo", sort=False):
        family = str(group["family"].iloc[0])
        ax.plot(
            group["FAR (%)"],
            group["FRR (%)"],
            marker="o",
            linewidth=1.4,
            alpha=0.72,
            color=family_palette.get(family),
            label=combo,
        )
    ax.set_title("DET Operating Points from Phase-1 Logs")
    ax.set_xlabel("FAR (%)")
    ax.set_ylabel("FRR (%) - lower is better")
    ax.set_xticks([1, 5])
    ax.set_xlim(0.7, 5.3)
    ax.set_ylim(0, min(100, max(det_points_df["FRR (%)"]) + 4.0))
    ax.grid(True, axis="both", alpha=0.35)
    ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5), fontsize=7, title="Combination")
    fig.tight_layout(rect=(0, 0, 0.72, 1))
    fig.savefig(out_dir / "det_operating_points.png", dpi=220)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(10, 5.5))
    sns.lineplot(
        data=plot_df,
        x="loss",
        y="ACC@1%FAR (%)",
        hue="family",
        style="family",
        markers=True,
        dashes=False,
        linewidth=2.2,
        ax=ax,
    )
    ax.set_title("Loss Effect Under Each Model/Frontend")
    ax.set_xlabel("Loss")
    ax.set_ylabel("ACC@1%FAR (%)")
    ax.set_ylim(68, max(74, plot_df["ACC@1%FAR (%)"].max() + 1.0))
    ax.legend(title="Model + Frontend", loc="best")
    fig.tight_layout()
    fig.savefig(out_dir / "loss_effect_lines.png", dpi=220)
    plt.close(fig)

    ranked = plot_df.sort_values("ACC@1%FAR (%)", ascending=True)
    fig, axes = plt.subplots(2, 2, figsize=(15, 10.5), sharey=True)
    dashboard_metrics = [
        ("ACC@1%FAR (%)", "ACC@1%FAR - higher is better"),
        ("ACC@5%FAR (%)", "ACC@5%FAR - higher is better"),
        ("Recall@5%FAR (%)", "1 - FRR@5%FAR - higher is better"),
        ("F1 (%)", "F1 - higher is better"),
    ]
    for ax, (col, title) in zip(axes.flat, dashboard_metrics):
        sns.barplot(
            data=ranked,
            y="combo",
            x=col,
            hue="family",
            dodge=False,
            palette=family_palette,
            ax=ax,
        )
        ax.set_title(title)
        ax.set_xlabel("")
        ax.set_ylabel("")
        ax.set_xlim(0, max(85, ranked[col].max() + 4.0))
        if ax.get_legend() is not None:
            ax.get_legend().remove()
        for container in ax.containers:
            ax.bar_label(container, fmt="%.1f", padding=2, fontsize=7)
    handles, labels = axes.flat[0].get_legend_handles_labels()
    fig.legend(handles, labels, title="Model + Frontend", loc="lower center", ncol=2)
    fig.suptitle("Full MSWC Phase-1 Research Dashboard", y=0.995)
    fig.tight_layout(rect=(0, 0.05, 1, 0.98))
    fig.savefig(out_dir / "research_metric_dashboard.png", dpi=220)
    plt.close(fig)

    if not effect_df.empty:
        key_effects = effect_df[
            effect_df["effect"].isin(["PCEN vs MFCC", "GE2E vs Triplet", "SCAF+GE2E vs GE2E"])
        ].copy()
        key_effects["delta_acc1_pp"] = key_effects["delta_acc1_pp"].astype(float)
        key_effects["label"] = key_effects["effect"] + " | " + key_effects["scope"]
        key_effects = key_effects.sort_values("delta_acc1_pp", ascending=True)
        fig, ax = plt.subplots(figsize=(12.5, 8))
        sns.barplot(
            data=key_effects,
            y="label",
            x="delta_acc1_pp",
            hue="effect",
            dodge=False,
            ax=ax,
        )
        ax.axvline(0, color="#222222", linewidth=1)
        ax.set_title("Key Ablation Effects on ACC@1%FAR")
        ax.set_xlabel("Delta ACC@1%FAR (percentage points)")
        ax.set_ylabel("")
        for container in ax.containers:
            ax.bar_label(container, fmt="%+.2f", padding=3, fontsize=8)
        ax.legend(title="Effect", loc="center left", bbox_to_anchor=(1.02, 0.5))
        fig.tight_layout(rect=(0, 0, 0.82, 1))
        fig.savefig(out_dir / "key_effect_delta_bars.png", dpi=220)
        plt.close(fig)


def effect_delta(effect_df: pd.DataFrame, effect: str, scope: str, col: str = "delta_acc1_pp") -> str:
    if effect_df.empty:
        return "N/A"
    hit = effect_df[(effect_df["effect"] == effect) & (effect_df["scope"] == scope)]
    if hit.empty:
        return "N/A"
    return f"{float(hit.iloc[0][col]):+.2f} pp"


def write_report(df: pd.DataFrame, effect_df: pd.DataFrame, out_dir: Path) -> None:
    ranked = df.sort_values("acc1_far", ascending=False).reset_index(drop=True)
    best = ranked.iloc[0]
    best_edgespot = ranked[ranked["model"] == "EdgeSpotFull T4"].iloc[0]
    dscnn_pcen_ge2e = metric_at(df, "DSCNN-L", "PCEN", "GE2E")
    edgespot_pcen_ge2e = metric_at(df, "EdgeSpotFull T4", "PCEN", "GE2E")

    dscnn_params = int(dscnn_pcen_ge2e["param_count"]) if dscnn_pcen_ge2e is not None else None
    edgespot_params = (
        int(edgespot_pcen_ge2e["param_count"]) if edgespot_pcen_ge2e is not None else None
    )

    lines: list[str] = []
    lines.append("# Phân tích ma trận Full MSWC phase-1\n")
    lines.append("## Phạm vi và cách đọc kết quả\n")
    lines.append(
        "- Đây là **phase-1 screening** để so sánh xu hướng giữa các tổ hợp "
        "model/frontend/loss. Tiêu chí chọn checkpoint là **GSC-dev ACC@1%FAR**; "
        "chưa được xem là kết luận cuối trên GSC-test100.\n"
    )
    lines.append(
        "- Thiết lập train: Full MSWC English, manifest giới hạn tối đa 20 file/từ, "
        "5 epochs, 150 episodes/epoch, 30-way x 10 samples.\n"
    )
    lines.append(
        "- Thiết lập đánh giá trong lúc train: GSC-dev, 10-shot, 3 repeated runs/checkpoint. "
        "Các số dưới đây lấy từ log thật trong thư mục `raw/`.\n"
    )
    lines.append("\n## Ranking chính\n")
    lines.append(
        f"- Tổ hợp tốt nhất trong phase-1: **{best['combo']}**, "
        f"ACC@1%FAR={pct(best['acc1_far']):.2f}%, "
        f"ACC@5%FAR={pct(best['acc5_far']):.2f}%, "
        f"F1={pct(best['f1_mean']):.2f}%.\n"
    )
    lines.append(
        f"- Tổ hợp EdgeSpot tốt nhất: **{best_edgespot['combo']}**, "
        f"ACC@1%FAR={pct(best_edgespot['acc1_far']):.2f}%, "
        f"ACC@5%FAR={pct(best_edgespot['acc5_far']):.2f}%, "
        f"F1={pct(best_edgespot['f1_mean']):.2f}%.\n"
    )
    if dscnn_params and edgespot_params:
        lines.append(
            f"- Số tham số đọc từ log: DSCNN-L khoảng **{dscnn_params:,}** tham số, "
            f"EdgeSpotFull T4 khoảng **{edgespot_params:,}** tham số. Vì vậy cần đọc "
            "kết quả EdgeSpot cùng với yếu tố kích thước/triển khai, không chỉ raw accuracy.\n"
        )
    top5 = ranked.head(5)[["combo", "best_epoch", "acc1_far", "acc5_far", "frr5_far", "f1_mean"]].copy()
    for col in ["acc1_far", "acc5_far", "frr5_far", "f1_mean"]:
        top5[col] = top5[col].map(lambda x: f"{pct(x):.2f}%")
    lines.append(markdown_table(top5))
    lines.append("\n\n## Bảng delta quan trọng\n")
    delta_rows = pd.DataFrame(
        [
            {
                "So sánh": "DSCNN-L: PCEN vs MFCC khi dùng GE2E",
                "Delta ACC@1%FAR": effect_delta(effect_df, "PCEN vs MFCC", "DSCNN-L + GE2E"),
                "Delta F1": effect_delta(effect_df, "PCEN vs MFCC", "DSCNN-L + GE2E", "delta_f1_pp"),
                "Ý nghĩa": "PCEN giúp rõ nhất khi loss đã khớp với prototype.",
            },
            {
                "So sánh": "EdgeSpotFull T4: PCEN vs MFCC khi dùng GE2E",
                "Delta ACC@1%FAR": effect_delta(effect_df, "PCEN vs MFCC", "EdgeSpotFull T4 + GE2E"),
                "Delta F1": effect_delta(effect_df, "PCEN vs MFCC", "EdgeSpotFull T4 + GE2E", "delta_f1_pp"),
                "Ý nghĩa": "MFCC làm mất một phần lợi thế time-frequency của EdgeSpot.",
            },
            {
                "So sánh": "DSCNN-L + PCEN: GE2E vs Triplet",
                "Delta ACC@1%FAR": effect_delta(effect_df, "GE2E vs Triplet", "DSCNN-L + PCEN"),
                "Delta F1": effect_delta(effect_df, "GE2E vs Triplet", "DSCNN-L + PCEN", "delta_f1_pp"),
                "Ý nghĩa": "GE2E ăn khớp hơn với inference theo centroid.",
            },
            {
                "So sánh": "EdgeSpotFull T4 + PCEN: GE2E vs Triplet",
                "Delta ACC@1%FAR": effect_delta(effect_df, "GE2E vs Triplet", "EdgeSpotFull T4 + PCEN"),
                "Delta F1": effect_delta(effect_df, "GE2E vs Triplet", "EdgeSpotFull T4 + PCEN", "delta_f1_pp"),
                "Ý nghĩa": "GE2E cũng là loss mạnh nhất trong nhánh EdgeSpot.",
            },
            {
                "So sánh": "DSCNN-L + PCEN: SCAF+GE2E vs GE2E",
                "Delta ACC@1%FAR": effect_delta(effect_df, "SCAF+GE2E vs GE2E", "DSCNN-L + PCEN"),
                "Delta F1": effect_delta(effect_df, "SCAF+GE2E vs GE2E", "DSCNN-L + PCEN", "delta_f1_pp"),
                "Ý nghĩa": "Hybrid hiện tại bị SCAF kéo xấu, cần tune trọng số/lịch train.",
            },
            {
                "So sánh": "EdgeSpotFull T4 + PCEN: SCAF+GE2E vs GE2E",
                "Delta ACC@1%FAR": effect_delta(effect_df, "SCAF+GE2E vs GE2E", "EdgeSpotFull T4 + PCEN"),
                "Delta F1": effect_delta(effect_df, "SCAF+GE2E vs GE2E", "EdgeSpotFull T4 + PCEN", "delta_f1_pp"),
                "Ý nghĩa": "Trong full-MSWC phase-1, GE2E đơn lẻ tốt hơn hybrid.",
            },
        ]
    )
    lines.append(markdown_table(delta_rows))
    lines.append("\n\n## Diễn giải theo hướng nghiên cứu\n")
    lines.append(
        "- **GE2E tốt nhất trong phase-1 vì objective khớp với cơ chế inference.** "
        "Hệ thống few-shot sau cùng dùng enrollment samples để tính prototype/centroid, "
        "rồi so khoảng cách L2 của query với các prototype. GE2E cũng huấn luyện embedding "
        "theo hướng gần centroid đúng lớp và xa centroid lớp khác, nên tín hiệu train và "
        "cách test nhất quán hơn Triplet.\n"
    )
    lines.append(
        "- **PCEN tốt hơn MFCC khi đi với GE2E**, đặc biệt ở DSCNN-L. PCEN giữ biểu diễn "
        "mel/time-frequency giàu hơn và có cơ chế nén động, chuẩn hóa biên độ theo thời gian. "
        "Điều này hợp với full MSWC vì dữ liệu nhiều người nói, mức âm lượng và nhiễu khác nhau. "
        "MFCC nén phổ mạnh hơn, hữu ích cho baseline cổ điển nhưng có thể làm mất chi tiết "
        "mà CNN/EdgeSpot cần khai thác.\n"
    )
    lines.append(
        "- **SCAF và SCAF+GE2E chưa thắng trong full-MSWC phase-1.** Lý do hợp lý nhất "
        "không phải là SCAF vô dụng, mà là cấu hình phase-1 quá ngắn và quá rộng: 37k+ train words, "
        "mỗi word tối đa 20 file, chỉ 5 epochs. SCAF là margin/angular classification loss, "
        "thường cần lịch train ổn định hơn, class sampling/tuning tốt hơn, và cần cân bằng trọng số "
        "khi ghép với GE2E. Trong log hiện tại, SCAF+GE2E bị thấp hơn GE2E đơn lẻ, cho thấy trọng số "
        "hybrid hiện tại có thể làm embedding lệch khỏi tiêu chí centroid của bước inference.\n"
    )
    lines.append(
        "- **EdgeSpotFull T4 + MFCC là ablation kiểm tra, không phải cấu hình chính.** "
        "EdgeSpot được thiết kế để tận dụng biểu diễn time-frequency giàu hơn; khi đổi sang MFCC, "
        "lợi thế kiến trúc giảm rõ. Nhánh EdgeSpot tốt nhất vẫn là **EdgeSpotFull T4 + PCEN + GE2E**.\n"
    )
    lines.append(
        "- **DSCNN-L + PCEN + GE2E thắng phase-1 nhưng chưa tự động thay kết luận Microset.** "
        "Microset và Top500/Full-MSWC khác nhau về dữ liệu, số từ, sampling và độ dài train. "
        "Do đó kết quả này nên dùng để chọn shortlist cho train dài hơn/test100, không dùng để phủ định "
        "mốc Microset nếu chưa chạy cùng protocol cuối.\n"
    )
    lines.append("\n## Cách dùng biểu đồ trong báo cáo\n")
    lines.append(
        "- `all_metric_heatmap.png`: đặt nhiều giá trị vào cùng một biểu đồ; phù hợp nhất để nhìn tổng thể "
        "ACC@1%FAR, ACC@5%FAR, AUC, open-set ACC, keyword ACC, F1, 1-EER và 1-FRR@5%.\n"
    )
    lines.append(
        "- `research_metric_dashboard.png`: dashboard 4 metric chính; dễ trình bày khi muốn so sánh nhanh "
        "ACC@1%FAR, ACC@5%FAR, recall tại 5% FAR và F1.\n"
    )
    lines.append(
        "- `acc1far_interaction_heatmap.png`: biểu đồ tương tác model/frontend/loss; dùng để giải thích "
        "vì sao GE2E và PCEN nổi bật hơn trong phase-1.\n"
    )
    lines.append(
        "- `key_effect_delta_bars.png`: biểu đồ delta; dùng để nói rõ thêm PCEN hơn MFCC bao nhiêu, "
        "GE2E hơn Triplet bao nhiêu, và SCAF+GE2E đang kém GE2E bao nhiêu.\n"
    )
    lines.append(
        "- `det_curve_summary.md`: bảng DET summary theo EER, dùng để đọc trực tiếp "
        "AUC/EER/FRR tại các operating points 1% FAR và 5% FAR.\n"
    )
    lines.append(
        "- `det_summary_heatmap.png` và `det_operating_points.png`: hai hình DET summary; "
        "hình operating-points nối hai điểm FAR=1% và FAR=5% vì log phase-1 không lưu raw scores "
        "để dựng đường DET liên tục.\n"
    )
    lines.append("\n## Kết luận thực nghiệm phase-1\n")
    lines.append(
        "Cấu hình nên ưu tiên train/evaluate tiếp là **DSCNN-L + PCEN + GE2E** và "
        "**EdgeSpotFull T4 + PCEN + GE2E**. Nếu mục tiêu luận văn là hệ thống gọn cho edge/device, "
        "EdgeSpotFull T4 vẫn có giá trị vì nhỏ hơn đáng kể; nếu mục tiêu là điểm dev phase-1 cao nhất, "
        "DSCNN-L + PCEN + GE2E đang dẫn đầu. Bước chuẩn nghiên cứu tiếp theo là train dài hơn cho shortlist, "
        "sau đó chạy GSC-test100 và báo cáo mean/std thay vì chỉ dùng phase-1 dev.\n"
    )
    lines.append("\n## File đầu ra\n")
    lines.append("- `matrix_best_epoch_metrics.csv/md`: bảng metric tốt nhất theo từng combo.\n")
    lines.append("- `matrix_effect_deltas.csv/md`: bảng delta giữa các lựa chọn frontend/loss/model.\n")
    lines.append("- `det_curve_summary.csv/md`: bảng DET summary theo EER và FRR operating points.\n")
    lines.append("- `acc1far_ranked_bar.png`: ranked single-metric comparison.\n")
    lines.append("- `acc1far_interaction_heatmap.png`: model/frontend/loss interaction.\n")
    lines.append("- `all_metric_heatmap.png`: all comparable metrics in one view.\n")
    lines.append("- `loss_effect_lines.png`: loss behavior under each model/frontend.\n")
    lines.append("- `research_metric_dashboard.png`: 4 metric chính trong cùng dashboard.\n")
    lines.append("- `key_effect_delta_bars.png`: delta ACC@1%FAR cho các ablation chính.\n")
    lines.append("- `det_summary_heatmap.png`: bảng DET summary dạng ảnh.\n")
    lines.append("- `det_operating_points.png`: hình operating-point DET tại FAR=1% và FAR=5%.\n")
    (out_dir / "full_mswc_matrix_analysis_vi_notes.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw-dir", type=Path, default=Path("reports/full_mswc_matrix_analysis/raw"))
    parser.add_argument("--out-dir", type=Path, default=Path("reports/full_mswc_matrix_analysis"))
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    log_paths = [
        args.raw_dir / "full_mswc_12_combo_phase1_e5_ep150_manifest20.log",
        args.raw_dir / "full_mswc_12_combo_phase1_e5_ep150_manifest20_resume.log",
    ]
    tsv_paths = [
        args.raw_dir / "full_mswc_12_combo_phase1_e5_ep150_manifest20_runs.tsv",
        args.raw_dir / "full_mswc_edgespot_mfcc_4_combo_phase1_e5_ep150_manifest20_runs.tsv",
    ]
    experiments = parse_logs(log_paths)
    status = load_status(tsv_paths)
    df = build_table(experiments, status)
    if df.empty:
        raise SystemExit("No experiments with GSC-dev metrics were parsed.")
    save_tables(df, args.out_dir)
    save_det_summary_tables(df, args.out_dir)
    effect_df = save_effect_tables(df, args.out_dir)
    save_plots(df, effect_df, args.out_dir)
    write_report(df, effect_df, args.out_dir)
    print(f"Wrote {len(df)} experiment rows to {args.out_dir}")
    print(df.sort_values("acc1_far", ascending=False)[["combo", "best_epoch", "acc1_far", "acc5_far", "frr5_far"]].to_string(index=False))


if __name__ == "__main__":
    main()
